name: yt-grabber-tui
base: core24
confinement: classic
grade: stable
version: '1.1-rc'
summary: "TUI утилита для скачивания видео и аудио"
description: |
  Yt-grabber-tui — легкая TUI утилита на основе FTXUI.

apps:
  yt-grabber-tui:
    command: bin/yt-grabber-tui
    environment:
      LD_LIBRARY_PATH: $SNAP/libs
    plugs:
      - network
      - network-bind
      - removable-media

hooks:
  post-refresh:
    command: usr/bin/snapcraft-preload --add-user-group $SNAP_USER_COMMON lxd

parts:
  yt-grabber-tui:
    plugin: dump
    source: .
    organize:
      bin/yt-grabber-tui: bin/yt-grabber-tui
      libs/*: libs/