name: Build Release

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake \
            libboost-all-dev \
            libfmt-dev \
            libspdlog-dev \
            git \
            cmake \
            pkg-config

      - name: Install FTXUI
        run: |
          git clone https://github.com/ArthurSonzogni/FTXUI.git
          cd FTXUI
          cmake -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=/usr \
            -DCMAKE_INSTALL_LIBDIR=lib \
            -DBUILD_SHARED_LIBS=OFF
          cmake --build build -j$(nproc)
          sudo cmake --install build
          cd ..

      - name: Build
        run: make