name: Test and build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake \
            libboost-all-dev \
            nlohmann-json3-dev \
            libfmt-dev \
            libspdlog-dev

      - name: Build
        run: make

      - name: Make executable
        run: chmod +x ./yt-grabber-tui || true

      - name: Run
        run: ./yt-grabber-tui
