name: Build YtGrabber-TUI Windows

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: MINGW64
          install: >
            base-devel
            unzip
            curl
            zip
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-fmt
            mingw-w64-x86_64-spdlog
            mingw-w64-x86_64-python
            mingw-w64-x86_64-boost

      - name: Set BOOST_ROOT
        run: echo "BOOST_ROOT=/mingw64" >> $env:GITHUB_ENV

      - name: Build YtGrabber-TUI
        shell: msys2 {0}
        run: |
          echo "Compiling YtGrabber-TUI..."
          g++ -Wall -O2 -std=c++17 -m64 -static-libgcc -static-libstdc++ \
            -Iinclude \
            -I${BOOST_ROOT}/include/boost \
            src/*.cpp \
            -L${BOOST_ROOT}/lib \
            -lboost_process-mt \
            -lboost_filesystem-mt \
            -lboost_system-mt \
            -lfmt -lspdlog -lwinpthread -lws2_32 \
            -o yt-grabber-tui.exe
          echo "Build completed successfully."

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: yt-grabber-tui-${{ github.sha }}
          path: yt-grabber-tui.exe