name: Build Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential \
            libboost-all-dev \
            libfmt-dev \
            libspdlog-dev \

      - name: Build
        run: make

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: yt-grabber-tui-${{ github.ref_name }}
          path: yt-grabber-tui
