name: Build Snap

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install snapcraft
        run: sudo snap install snapcraft --classic

      - name: Build Snap package
        uses: snapcore/action-build@v1
        id: build

      - name: Upload .snap as artifact
        uses: actions/upload-artifact@v4
        with:
          name: yt-grabber-tui_${{ github.ref_name }}_amd64.snap
          path: "*.snap"
          if-no-files-found: error